clc;
clear all;
close all;
fs=100;
t = (1:100) /fs;
s1 = sin(2*pi*5*t);
subplot (4,1,1);
plot(t, s1);
title('sl = sin(2*pi*5*t)');
xlabel('TIME');
ylabel ('AMPLITUDE');
s2 = sin(2*pi*15*t);
subplot (4,1,2);
plot(t, s2);
title('s2 = sin(2*pi*15*t)');
xlabel('TIME');
ylabel ('AMPLITUDE');
s3 = sin(2*pi*30*t);
subplot (4,1,3);
plot(t, s3);
title('s3 = sin(2*pi*30*t)');
xlabel('TIME');
ylabel ('AMPLITUDE');
s = s1+s2+s3;
subplot (4,1, 4);
plot(t,s);
title('S = s1+s2+s3');
xlabel('TIME');
ylabel ('AMPLITUDE');
Wn = [10 20]*2/fs;
[b, a] = butter (4, Wn);
[h, w] = freqz (b, a, 512);
figure (2);
plot (w*fs/(2*pi), abs (h));
title('RESPONSE OF BUTTERWORTH FILTER');
xlabel ('FREQUENCY (in Hz)');
ylabel('GAIN in dB');
sf = filter (b,a,s);
figure (3);
subplot (2,1,1);
plot (sf);
title('FILTERED OUTPUT');
xlabel('TIME');
ylabel('AMPLITUDE');
s = fft (s,512);
sf = fft (sf,512);
p = (0:255)/256*(fs/2);
subplot (2,1,2);
plot(p, abs([s(1:256)' sf(1:256)']));
title('FREQUENCY SPETRUM OF FILTERED SIGNAL');
xlabel('FREQUENCY (in Hz)');
ylabel ('PSD');
